# --- 1. 物理机器定义 (Physical Servers) ---
# 依赖本地 ~/.ssh/config 中的配置
[all_vps]
ans-hk01
control_node ansible_connection=local ansible_python_interpreter=/usr/bin/python3

# --- 2. 逻辑角色分配 (Functional Roles) ---
[hub]
ans-hk01

[webservers]
# ans-hk02

[dbservers]
