# roles/common/vars/os/Debian.yml
# Tier 1 supported platforms: Ubuntu 20.04+, Ubuntu 22.04+
# Tier 2 supported platforms: Debian 11 (bullseye), Debian 12 (bookworm)

---
_common__os_packages:
  - apt-transport-https
  - gnupg2
  - lsb-release
  - software-properties-common

_common__service_manager: systemd
_common__pkg_mgr: apt
_common__ssh_service: ssh
_common__cron_service: cron
_common__firewall_pkg: ufw
_common__firewall_service: ufw
